# Generated by Django 5.1.3 on 2024-11-21 23:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name="keyword",
            name="word",
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="course",
            name="categories",
            field=models.ManyToManyField(blank=True, to="courses.category"),
        ),
        migrations.AddField(
            model_name="course",
            name="tags",
            field=models.ManyToManyField(blank=True, to="courses.tag"),
        ),
        migrations.AddField(
            model_name="keyword",
            name="tags",
            field=models.ManyToManyField(blank=True, to="courses.tag"),
        ),
    ]
